# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Jigsaw.OutlineClient
PackageVersion: 1.13.1
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://s3.amazonaws.com/outline-releases/client/windows/stable/Outline-Client.exe
  InstallerSha256: 5615D293850A4C4A15C31B3AAD262A29AB8B676A4DD1305D186D000EE6042590
ManifestType: installer
ManifestVersion: 1.6.0
