# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SnapNet.SnapNet
PackageVersion: 0.28.0.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stijnvdb88/Snap.Net/releases/download/v0.28.0.0/Snap.Net-0.28.0.0-Setup.exe
  InstallerSha256: DD424CBF273AF2DB7669147CAB1BFCFFA13B7BE9B5F3FAE1F19C500863BBC42C
ManifestType: installer
ManifestVersion: 1.6.0
